import { Inter } from "next/font/google";
import "./globals.css";
import { ColorSchemeScript, MantineProvider, createTheme } from "@mantine/core";
import '@mantine/core/styles.css';
import Navbar from "./(Components)/navbar/page";
import Footer from "./(Components)/footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Aviral Srivastava",
  description: "Generated by create next app",
};

const theme = createTheme({
  breakpoints: {
    xs: '30em',
    sm: '48em',
    md: '64em',
    lg: '74em',
    xl: '90em',
  },
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" 
    //  data-mantine-color-scheme="light"
     >
      <body className={inter.className}>
      {/* <ColorSchemeScript forceColorScheme="light" /> */}
        <MantineProvider
         theme={theme} 
        //  defaultColorScheme="light"
         defaultColorScheme="dark"
         >
          <Navbar />
          {children}
          <Footer />
        </MantineProvider>
      </body>
    </html>
  );
}